FROM common AS base

# Directory for Rust artifacts.
ENV RELEASE_DIR=/src/target/${TARGET}/release

# Name of the crate containing the pivot app binary.
ENV APPLICATION_CRATE_NAME=signed_echo

ADD . /src

# Pre-fetch workspace dependencies so the release build can run offline.
WORKDIR /src
RUN cd /src && cargo fetch

FROM base AS build
WORKDIR /src/src/${APPLICATION_CRATE_NAME}
RUN --network=none <<-EOF
	set -eux
	cargo build ${CARGOFLAGS}
	mkdir -p /rootfs
	mv ${RELEASE_DIR}/${APPLICATION_CRATE_NAME} /rootfs/tvc_app
	file /rootfs/tvc_app | grep "static-pie"
	sha256sum /rootfs/tvc_app | awk '{print "SHA256=" $1}'
	find /rootfs -exec touch -hcd "@0" "{}" +
EOF

FROM stagex/core-busybox:1.36.1@sha256:cac5d773db1c69b832d022c469ccf5f52daf223b91166e6866d42d6983a3b374 AS package
COPY --from=build /rootfs/. .
RUN echo "TVC application binary is available within the container image at /tvc_app"
RUN sha256sum /tvc_app | awk '{print "SHA256=" $1}'
