[package]
name = "reshard_host"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
qos_core           = { workspace = true }
qos_host_primitives= { workspace = true }
health_check       = { workspace = true }
attestation        = { workspace = true }
generated          = { workspace = true, features = ["tonic_types"] }
metrics            = { workspace = true }

tokio   = { workspace = true, features = ["macros","rt-multi-thread","signal"], default-features = false }
futures = { workspace = true }

[features]
vsock = ["qos_core/vm"]
