[package]
name = "reshard_host"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
qos_core = { path = "../../qos_core" }
qos_host_primitives = { path = "../../qos_host_primitives" }
health_check = { path = "../../health_check" }
attestation = { path = "../../attestation" }
generated = { path = "../../generated", features = ["tonic_types"] }
metrics = { path = "../../metrics" }

tokio = { version = "=1.43.1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
], default-features = false }
futures = "0.3"

[features]
vsock = ["qos_core/vm"]
