[package]
name = "qos_nsm_fuzz"
version = "0.0.0"
publish = false
edition = "2021"
rust-version = "1.88"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

qos_hex = { path = "../../qos_hex" }

# we need some of the mock code features
qos_nsm = { path = "../", features = ["mock"] }


# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
# enable arithmetic checks at runtime
overflow-checks = true

[[bin]]
name = "1_attestation_doc_from_der"
path = "fuzz_targets/1_attestation_doc_from_der.rs"
test = false
doc = false
bench = false

[[bin]]
name = "2_verify_attestation_doc_against_user_input"
path = "fuzz_targets/2_verify_attestation_doc_against_user_input.rs"
test = false
doc = false
bench = false
