build:
  command: make
sign:
  files:
    - out/qos_client/index.json
    - out/qos_enclave/index.json
    - out/qos_host/index.json
    - out/digests.txt
  format: raw
  method: ssh
  backing: disk
storage:
  method: git
  location: git@github.com:tkhq/repros-sigs.git
  path: /qos
