apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - service.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: qos.turnkey.io=app
    path: deployment.yaml
