FROM common AS base
ADD . /src

FROM base AS build
ENV PCSC_LIB_NAME=static=pcsclite
RUN <<-EOF
	set -eux
	env -C /src/qos_client cargo build --features smartcard ${CARGOFLAGS}
	cp /src/target/${TARGET}/release/qos_client /
	file /qos_client | grep "static-pie"
EOF

FROM base AS install
WORKDIR /rootfs
COPY --from=build /qos_client .
RUN find . -exec touch -hcd "@0" "{}" +

FROM scratch AS package
COPY --from=install /rootfs .
ENTRYPOINT ["/qos_client"]
