//! Small SDK for QOS WASM meta-pivot examples.
//!
//! Policy and function authors should test normal Rust functions. The ABI
//! module is glue generated by macros for the WASM build.

use borsh::{BorshDeserialize, BorshSerialize};

pub mod abi;

#[derive(BorshDeserialize, BorshSerialize, Debug, Clone, PartialEq, Eq)]
pub struct PolicyContext {
	pub function_hash: [u8; 32],
	pub function_wasm: Vec<u8>,
	pub input_hash: [u8; 32],
	pub input: Vec<u8>,
}

#[derive(BorshDeserialize, BorshSerialize, Debug, Clone, PartialEq, Eq)]
pub enum Decision {
	Allow,
	Deny { reason: String },
}

impl Decision {
	pub fn allow() -> Self {
		Self::Allow
	}

	pub fn deny(reason: impl Into<String>) -> Self {
		Self::Deny { reason: reason.into() }
	}

	pub fn is_allowed(&self) -> bool {
		matches!(self, Self::Allow)
	}
}
