FROM qos-local/build-base as base

COPY --from=ghcr.io/tkhq/qos_client  /qos_client /usr/local/bin/
COPY --from=stagex/curl . /
COPY --from=stagex/bash . /
COPY --from=stagex/kubectl . /

ADD images/enclave_reshard/scripts/* /usr/local/bin/

ADD images/enclave_reshard/nitro.pcrs /qos-dist/aws-x86_64.pcrs

USER 1000:1000