name: "Set up LFS"
description: "Ensure git-lfs and tkinfra are installed and configured"
inputs:
  pullLFSObjects:
    type: boolean
    description: also pull LFS objects
    default: false
  monoSshKey:
    description: ssh key for cloning mono
    type: string

runs:
  using: "composite"
  steps:
    - name: Install git lfs
      run: sudo apt-get install git-lfs -y
      shell: bash

    - name: tkinfra cache
      id: tkinfra-cache
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        key: tkinfra-${{ runner.os }}-${{ hashFiles('src/go/tkinfra/**') }}
        path: /usr/local/bin/tkinfra

    - name: Set up Go
      if: steps.tkinfra-cache.outputs.cache-hit != 'true'
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: '1.21'
        cache: false

    - name: Clone mono
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: tkhq/mono
        ssh-key: ${{ inputs.monoSshKey }}
        submodules: false
        lfs: false
        sparse-checkout: |
          src
        path: mono

    - name: Build `tkinfra`
      if: steps.tkinfra-cache.outputs.cache-hit != 'true'
      shell: 'script -q -e -c "bash {0}"'
      run: |
        cd mono/src/go/tkinfra
        go mod download
        GOBIN=/usr/local/bin go install ./cmd/tkinfra

    - name: Configure `git-lfs` for `tkinfra`
      shell: 'script -q -e -c "bash {0}"'
      run: |
        git config lfs.customtransfer.tks3.path tkinfra
        git config lfs.customtransfer.tks3.args "lfs --default-credentials"
        git config lfs.standalonetransferagent tks3

    - name: Pull LFS artifacts
      shell: 'script -q -e -c "bash {0}"'
      run: |
        git lfs pull
