ARG BASE_IMAGE=common
FROM ${BASE_IMAGE} as base_image
FROM common as base

ADD . /src

FROM base as build-benchmarking
RUN <<-'EOF'
	set -eux
	env -C /src/benchmarking cargo build ${CARGOFLAGS}
	cp /src/benchmarking/target/${TARGET}/release/benchmarking /
	file /benchmarking | grep "static-pie"
EOF

FROM scratch as package
COPY --from=build-benchmarking /benchmarking .
ENTRYPOINT ["/benchmarking"]
