apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../../base/qos_enclave

patches:
  - target:
      group: benchmarking
      version: v1
      kind: Deployment
      labelSelector: qos.turnkey.io=benchmarking
    path: deployment.yaml
