[package]
name = "qos_bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
qos_core = { workspace = true, default-features = false }

# Third party
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }

[features]
qemu = ["qos_core/qemu"]
egress = ["qos_core/egress"]
