# This is using an old version of pcsc-lite since upgrading to v2.2.3 broke
# static builds. Once we have confirmed an updated pcsc-lite has fixed this
# issue, we should upgrade this again.
FROM stagex/pcsc-lite:sx2024.03.0@sha256:e720e1795706c7c8c1db14bf730b10521e3ff42e4bed90addc590f7446aac8af AS pcsc-lite
FROM stagex/pallet-rust:1.88.0@sha256:81c39a3b42b0336e439aee3c90e9e1e4da1d32425451e7222198a978eb8c2623 AS rust
FROM stagex/user-file:5.45@sha256:07ebef1a7d375c785c2268c5532b473a7130e4fbcf9807cc8f7b5d61e3b84b74 AS file
FROM stagex/core-make:4.4@sha256:45523d7f448c58a2a1159b578a0c838010dac9b9a59bdd02f1e4dc533e618de6 AS make

FROM scratch AS base

COPY --from=pcsc-lite . /
COPY --from=rust . /
COPY --from=file . /
COPY --from=make . /

COPY --chmod=644 <<-EOF /etc/passwd
	root:x:0:0:root:/root:/bin/sh
	user:x:1000:1000::/home/user:/bin/sh
EOF
COPY --chmod=644 <<-EOF /etc/group
	root:x:0:
	user:x:1000:
EOF

RUN mkdir -p /rootfs/etc
RUN mkdir -p /rootfs/home/user
RUN chown -R user:user /rootfs/home/user

RUN touch -hcd "@0" /etc/group /etc/hpasswd
ENV TZ=UTC
ENV LANG=C.UTF-8
ENV LC_ALL=C
ENV USER=user
ENV HOME=/home/user
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ENV TARGET=x86_64-unknown-linux-musl
ENV RUSTFLAGS="-C target-feature=+crt-static"
ENV CARGOFLAGS="--locked --no-default-features --release --target ${TARGET}"

WORKDIR /src
