[package]
name = "reshard_app"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "reshard_app"
path = "src/lib.rs"

[features]
mock  = ["qos_core/mock", "qos_nsm/mock_realtime"]
vsock = ["qos_core/vm"]

[dependencies]
qos_core   = { workspace = true }
qos_crypto = { workspace = true }
qos_p256   = { workspace = true }
qos_nsm    = { workspace = true }
qos_net    = { workspace = true }
qos_hex    = { workspace = true }
generated  = { workspace = true }

http            = { workspace = true, default-features = false }
httparse        = { workspace = true, default-features = false }
url             = { workspace = true, default-features = false }
rustls          = { workspace = true, features = ["std","aws_lc_rs","tls12"], default-features = false }
webpki-roots    = { workspace = true, default-features = false }
chunked_transfer= { workspace = true, default-features = false }
borsh           = { workspace = true, features = ["std","derive"], default-features = false }
serde           = { workspace = true, features = ["derive"], default-features = false }
serde_json      = { workspace = true, default-features = false }

[dev-dependencies]
reshard_app = { path = ".", features = ["mock"] }
