name: stagex-build CI # build check for PR and main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build artifacts
    runs-on: ubicloud-standard-16
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Docker
        uses: ./.github/actions/docker-setup
        with:
          ghcr: ${{ secrets.GITHUB_TOKEN }}

      - name: Run `make`
        shell: 'script -q -e -c "bash {0}"'
        run: make -j$(nproc)
