FROM common AS base
ADD . /src

FROM base AS build
RUN <<-EOF
	set -eux
	cd /src/qos_client
	cargo build --features vm ${CARGOFLAGS}
	cp /src/target/${TARGET}/release/qos_host /
	file /qos_host | grep "static-pie"
EOF

FROM base AS install
WORKDIR /rootfs
COPY --from=build /qos_host .
RUN find . -exec touch -hcd "@0" "{}" +

FROM scratch AS package
COPY --from=install /rootfs .
ENTRYPOINT ["/qos_host"]
